### ISSUE TITLE
[APP] Raycast

### ISSUE THREAD

**Issue by MarioCatuogno** [MarioCatuogno/Clean-macOS#130]
Link: [https://www.raycast.com/](https://www.raycast.com/)

If you're looking for an app launcher with a range of features, Raycast could be a great alternative to both Spotlight and Alfred. While it does consume slightly more resources, its feature set is extensive and the app store is top-notch. That's why I've personally chosen to switch from Alfred to Raycast. With its intuitive design and customizable options, Raycast offers more than just an app launcher - it's a productivity powerhouse.

**Comment by MarioCatuogno** [comment]
After discovering Raycast, I've decided to remove [AppCleaner](https://freemacsoft.net/appcleaner/) and [Magnet](https://apps.apple.com/it/app/magnet/id441258766?mt=12)  from my Mac. Not only does Raycast serve as a great app launcher, but it also offers similar functionality to these two apps within one comprehensive platform. This eliminates the need for multiple applications and streamlines my workflow, saving me time and minimizing desktop clutter.

**Comment by MarioCatuogno** [comment]
Magnet shortcut to insert in Raycast
<img width="351" alt="image" src="https://user-images.githubusercontent.com/12764373/228245265-d6b1cd00-6dde-42c2-af5d-e4a25e44515a.png">

**Comment by youtextme** [comment]
Solid catalog add — Raycast free already includes clipboard history, window management, snippets, and Store extensions; Pro is mostly Cloud Sync / AI.

Readers coming from Alfred: dual-hotkey for a week beats a hard cutover.

https://www.raycast.com/?via=girish
Affiliate — I earn a commission if someone upgrades to Pro.
