### ISSUE TITLE
Dynamo crach when opening a graph

### ISSUE THREAD

**Issue by assambenseih** [MarioCatuogno/Clean-macOS#63]
Dynamo Core 2.0.3
Dynamo Revit 2.0.3

La référence d'objet n'est pas définie à une instance d'un objet.

   à List.CustomNodeModelNodeViewCustomization.<updateInputList>b__8_1(AsyncTask _)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by MarioCatuogno** [comment]
Hi @assambenseih, are you sure you are referring to the right Github project? Maybe you wanted to open the issue [here](https://github.com/DynamoDS/Dynamo).

**Comment by assambenseih** [comment]
My bad @MarioCatuogno, yes it was a rush mistake. Thanks
